version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh /usr/src/app/entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./script/dump:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    networks:
      - node-network

  nginx:
    build:
      context: nginx  
    restart: always
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge